// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type User struct {
	ID           interface{}
	Username     string
	Email        string
	PasswordHash string
	DateOfBirth  time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
