// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user (id, username, email, password_hash, date_of_birth)
VALUES (
	?1,
	?2,
	?3,
	?4,
	?5
)
RETURNING id, username, email, password_hash, date_of_birth, created_at, updated_at
`

type CreateUserParams struct {
	ID           interface{}
	Username     string
	Email        string
	PasswordHash string
	DateOfBirth  time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DateOfBirth,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user
WHERE id = ?1
`

func (q *Queries) DeleteUser(ctx context.Context, id interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, date_of_birth, created_at, updated_at FROM user
WHERE email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, date_of_birth, created_at, updated_at FROM user
WHERE username = ?1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDateOfBirth = `-- name: UpdateUserDateOfBirth :exec
UPDATE user
SET date_of_birth = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateUserDateOfBirthParams struct {
	DateOfBirth time.Time
	ID          interface{}
}

func (q *Queries) UpdateUserDateOfBirth(ctx context.Context, arg UpdateUserDateOfBirthParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDateOfBirth, arg.DateOfBirth, arg.ID)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE user
SET email = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateUserEmailParams struct {
	Email string
	ID    interface{}
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE user
SET password_hash = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           interface{}
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
